services:
- name: nginx
  url: http://bundler

bundles:
  authz:
    resource: bundles/authz.tar.gz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  console: true