_format_version: "2.1"

services:
- name: docs.microservice
  url: http://docs:3000
  routes:
  - name: docs
    methods:
    - POST
    strip_path: false
    paths:
    - /documents/*
    plugins:
    - name: opa-pass
      config:
        server:
          url: http://opa:8181/v1/data/authz/allow
        request:
          always_pass_forward: false
          body: false
